### ISSUE TITLE
Example in README no longer reflects the API of cl-async

### ISSUE THREAD

**Issue by fade** [orthecreedence/drakma-async#30]
Thanks for the excellent project! I was hoping you could recast the example in the README file in terms of your blackbird promises library, since cl-async no longer includes any of the macros referenced in the drakma-async example... the interface to blackbird seems quite different than what used to be in cl-async.

**Comment by orthecreedence** [comment]
Not a problem! I'll most likely get around to this tomorrow night or sometime this weekend. Thanks for bringing it to my attention =].

**Comment by orthecreedence** [comment]
Hope this clears things up, let me know if you have any questions about blackbird. A lot of the concepts are the same as the old cl-async-future project (they share a common base) but error handling has changed quite a bit in blackbird.
